### ISSUE TITLE
Special characers in Jitsi Meet session ID

### ISSUE THREAD

**Issue by blinard-BIOINFO** [timetheoretical/jitsi-meet-outlook#11]
So it seems Jitsi does not allow special chracters in the ID of a meeting.
While this is not a problem per say, the current plugin allow special characters in the ID field and generate a broken URL link if any special character is entered by the user. From my experience, this is definitely a common scenario for latin languages, which have many accents.

A suggestion for a rapid fix: 
- test if the string entered by the user in the ID field is matching the regular expression [a-zA-Z0-9_]+ . 
- If not, pop up an error message asking to remove all special characters (to the exception of '_') and reset the ID field to an empty string, whitout generatin the URL in the event.

**Comment by timetheoretical** [comment]
Agree with the issue and proposed solution. Will implement this when I get time. Thanks!

**Comment by timetheoretical** [comment]
@blinard-BIOINFO, I have now implemented your solution in [v0.6.0](https://github.com/timetheoretical/jitsi-meet-outlook/releases/tag/v0.6.0). Instead of popping up a warning window, I opted to silently remove any illegal characters (defined by the regex rule you proposed).

Before applying the above filter, any accented characters are replaced by their non-accented equivalents (as mentioned in #7).
