### ISSUE TITLE
Update of already installed plugin doesnt replace it

### ISSUE THREAD

**Issue by philippe-ritter** [timetheoretical/jitsi-meet-outlook#21]
Hello

I see today that on my PC, I just installed version 0.5.1, and I see two New Jitsi Meeting button.
I go to add/remove Programm, and found 3 installation of your plug-in : 0.2.0, 0.3.0 and 0.5.1
Can you add an check to replace the already installed version ?

Thank you and regards
Philippe

**Comment by timetheoretical** [comment]
Hi there,

This is actually due to the switch in installer frameworks done in v0.5.0; the new installers will not detect installations of versions prior to v0.5.0, and vice-versa. However, the new installers should detect installations of v0.5.0 or higher, which will hinder the situation you describe with parallell installations.

I have added a disclaimer noting this issue in the [v0.5.0](/timetheoretical/jitsi-meet-outlook/releases/tag/v0.5.0) release.
