### ISSUE TITLE
Convert to "Office Add-ins"

### ISSUE THREAD

**Issue by divialth** [timetheoretical/jitsi-meet-outlook#29]
Perhaps a very bit feature request which will not get accepted, but lets give it a try :)

As far as I can see this is a VSTO type Plugin for Outlook (correct me if I am wrong)
Would it be possible to convert this Plugin to a "Office Add-in"?

Currently this (really great) plugin is tied to the Windows platform. But Outlook is available to different platforms in which VSTO plugins are not supported.
For example I am using Outlook daily on a Mac, and here it is only possible to use "Office Add-Ins".

I think that would also fix #25 and perhaps some other problems, like central deployment and such things.

But to be clear: I do not have any idea if it technical possible or not :)

**Comment by timetheoretical** [comment]
You're right that this is a VSTO type plugin. It is absolutely technically possible to convert the addin to an "Office (Web) Add-In". However, that would require rewriting the plugin from scratch in JavaScript/TypeScript.

I share your view in that it would be preferable to reach a larger audience (also mac and web-users) and that it could simplify deployment and related issues (e.g. #10). However, it is still unclear to me how the deployment could work for admins who want to pre-configure the plugin for their users (see e.g. #2). Perhaps it would be possible to sideload the plugin instead of getting it from the Microsoft Store.

It seems to me that Office (web) add-ins will be the "main" plug-in development platform for the future, so I will seriously consider this before continuing development on this add-on. Unfortunately, the time I can spend on this project over the next half-year is quite limited.

Thanks for flagging this :)

**Comment by timetheoretical** [comment]
I have looked a bit further into this, and, unfortunately, it seems that Microsoft web addins need to be hosted on a server. See for example [this ](https://stackoverflow.com/questions/40513774/office-add-in-web-app-can-be-completely-offline-without-web-server) Stackoverflow post. 

This is beyond my ambition, so I will not convert this into a web addin.
