### ISSUE TITLE
Impossible to add a custom port in custom domain name

### ISSUE THREAD

**Issue by blinard-BIOINFO** [timetheoretical/jitsi-meet-outlook#5]
Hi,
My local configuration of jitsi uses a custom port, that I would like to insert  in the generated URL.
However, the current custom domain field does not allow for the : symbol

It could be useful to add 2 more fields in the Jitsi Meet Settings.

1. port
2. default meeting name 

The second is useful for users forgetting to change the meeting ID field. So that there are ending in a preconfigured dummy room, not an ongoing meeting.

At the end, this default URL adress would be generated :
https://my.domain:port/my_default_meeting_room

Port does not necessarily have to appear in the hyperlink string, but just in the actual hyperlink.

As suggested in #4, these could also be set at installation.

**Comment by timetheoretical** [comment]
Hi,

Thanks, these are good ideas.

> 1. port

As of [v0.3.0](/timetheoretical/jitsi-meet-outlook/releases/tag/v0.3.0), I have now made it such that the domain name validity check allows for a port specification (e.g. :8080).

> 2. default meeting name

I have also added the possibility to specify a default room ID that new appointments will be assigned, instead of a random ID.

> Port does not necessarily have to appear in the hyperlink string, but just in the actual hyperlink.

As it stands now, the appointments that are being generated by the plugin are in plaintext. It is my plan to enable RTF/HTML in the appointments, which could facilitate hiding the url.

> As suggested in #4, these could also be set at installation.

I'm aiming to make all settings preconfigurable in a silent install.
